server {
    listen 80;

    server_name _ localhost kupipodariday.isaac.nomorepartiessite.ru;

    root /usr/share/nginx/html;
    
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
    location ~* \.(?:js|css|png|jpe?g|gif|svg|ico|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
